### ISSUE TITLE
Additional parameters misnaming

### ISSUE THREAD

**Issue by YevhenKi** [Bercon/BerconMaps#42]
The second additional parameter is named as "Random seed" by must be "Channel" 
![ParamMisnaming](https://user-images.githubusercontent.com/107002068/232740167-c7b73ee1-34ff-4601-8a67-0b3d44e84b74.png)

**Comment by feathered-arch** [comment]
`xyz_chan,	_M("xyz_chan"), TYPE_INT, P_ANIMATABLE, IDS_SEED, 
		p_default, 1, p_range, 0, 100,
		p_ui, TYPE_SPINNER,	EDITTYPE_INT, IDC_CHAN, IDC_CHAN_SPIN, SPIN_AUTOSCALE, 
		p_end,`

Yep, in [BerconCommon.h](https://github.com/Bercon/BerconMaps/blob/6da350a70018a23c6e42658f4305ea47b72be0d7/src/BerconCommon.h#L153) it shouldn't be IDS_SEED, but for the life of me I'm not sure what [src/resource.h](https://github.com/Bercon/BerconMaps/blob/6da350a70018a23c6e42658f4305ea47b72be0d7/src/resource.h) it should be instead.

(it's been this way since 3.03! huh....)

**Comment by Bercon** [comment]
Should be fixed in https://github.com/Bercon/BerconMaps/pull/52
